{"uuid": "b2fa1289-7e38-43e1-af16-eab97abd2166", "children": ["957b26c4-0aae-4c78-83e1-ffa347eb06eb"], "befores": [{"name": "open_browser", "status": "passed", "start": 1674207891838, "stop": 1674207898855}], "afters": [{"name": "open_browser::0", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.InvalidSessionIdException: Message: invalid session id\nStacktrace:\n#0 0x55873fec8013 <unknown>\n#1 0x55873fc2a89f <unknown>\n#2 0x55873fc53a1b <unknown>\n#3 0x55873fc7e8ac <unknown>\n#4 0x55873fc7c591 <unknown>\n#5 0x55873fc7bdc7 <unknown>\n#6 0x55873fc01c54 <unknown>\n#7 0x55873fc02aa0 <unknown>\n#8 0x55873fef5e5d <unknown>\n#9 0x55873ff0f061 <unknown>\n#10 0x55873fef7bb5 <unknown>\n#11 0x55873ff0fe08 <unknown>\n#12 0x55873feeb2f0 <unknown>\n#13 0x55873fc017d2 <unknown>\n#14 0x7fd9a6d080b3 <unknown>\n\n", "trace": "  File \"/Users/irina/PycharmProjects/qa_quru_jenkins/venv/lib/python3.11/site-packages/allure_commons/_allure.py\", line 221, in __call__\n    return self._fixture_function(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/irina/PycharmProjects/qa_quru_jenkins/venv/lib/python3.11/site-packages/_pytest/fixtures.py\", line 917, in _teardown_yield_fixture\n    next(it)\n  File \"/Users/irina/PycharmProjects/qa_quru_jenkins/qa_guru_pageObjects_3_9/tests/conftest.py\", line 39, in open_browser\n    attach.add_html(browser)\n  File \"/Users/irina/PycharmProjects/qa_quru_jenkins/qa_guru_pageObjects_3_9/demoqa_tests/utils/attach.py\", line 16, in add_html\n    html = browser.driver.page_source\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/irina/PycharmProjects/qa_quru_jenkins/venv/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 539, in page_source\n    return self.execute(Command.GET_PAGE_SOURCE)['value']\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/irina/PycharmProjects/qa_quru_jenkins/venv/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 428, in execute\n    self.error_handler.check_response(response)\n  File \"/Users/irina/PycharmProjects/qa_quru_jenkins/venv/lib/python3.11/site-packages/selenium/webdriver/remote/errorhandler.py\", line 243, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1674207915833, "stop": 1674207916052}], "start": 1674207891838, "stop": 1674207916053}